language: objective-c

os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.2
env:
  - BUILD="gem install cocoapods && pod repo update && pod install && set -o pipefail && (xcodebuild -workspace DaylightUtils.xcworkspace -scheme DaylightUtils -destination 'platform=iOS Simulator,name=iPhone 8' build) | xcpretty"
  - BUILD="carthage bootstrap --platform ios && set -o pipefail && (xcodebuild -project DaylightUtils.xcodeproj -scheme DaylightUtils -destination 'platform=iOS Simulator,name=iPhone 8' build) | xcpretty"
  - BUILD="gem install cocoapods && pod repo update && pod lib lint DaylightUtils.podspec --verbose"
  - BUILD="carthage bootstrap --platform ios && carthage build --no-skip-current --platform iOS"

script: eval "${BUILD}"

notifications:
  slack: daylightltd:uZWZbjqQl3kta2sRv4bEkF6i
  email: false

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725

